local opt = vim.opt -- to set options
vim.o.background = "dark"
vim.cmd([[colorscheme gruvbox]])
opt.backspace = {"indent", "eol", "start"}
opt.clipboard = "unnamedplus"
opt.completeopt = "menu,menuone,noselect"
opt.cursorline = false
opt.cursorcolumn = false
opt.encoding = "utf-8"
opt.smarttab = true
opt.expandtab = true
opt.smartindent = true
opt.autoindent = true
opt.foldenable = false
opt.foldmethod = "indent"
opt.formatoptions = "l"
opt.hidden = true
opt.wrap = false
opt.hlsearch = true
opt.ignorecase = true
opt.inccommand = "split"
opt.incsearch = true
opt.joinspaces = false
opt.linebreak = true
opt.number = true
opt.list = false
opt.relativenumber = false
opt.scrolloff = 4
opt.shiftround = true
opt.shiftwidth = 4
opt.showmode = false
opt.sidescrolloff = 8
opt.signcolumn = "yes:1"
opt.smartcase = true
opt.smartindent = true
opt.spelllang = {"en_gb"}
opt.splitbelow = true
opt.splitright = true
opt.tabstop = 4
opt.termguicolors = true
opt.cc = "80"
opt.mouse = "a"
opt.ruler = true
opt.cmdheight = 2
opt.showtabline = 2
opt.virtualedit = "block"
opt.undofile = true
opt.undodir = vim.fn.stdpath("config") .. "/undo"
